name: gobenchdata publish
on: push
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: gobenchdata publish
      uses: bobheadxi/gobenchdata@v1
      with:
        PRUNE_COUNT: 100
        GO_TEST_FLAGS: -cpu 1,2
        PUBLISH: true
        PUBLISH_BRANCH: gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  cibuild:
    name: cibuild
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: script/generate --check
      - run: script/lint
  text-bench:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          repository: golang/text
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: "~1.15"
      - uses: WillAbides/benchdiff-action@v0
        with:
          benchdiff_version: 0.6.2
          status_sha: ${{ github.sha }}
          status_name: text-bench-result
          status_on_degraded: neutral
          benchdiff_args: |
            --packages ./unicode/...
            --cpu=1
            --count=10
            --warmup-count=1
            --benchtime=10ms
            --tolerance=50
            --base-ref v0.3.5
            --debug
